disk: part_efi: fix compile error due to strict-aliasing rules
This fixes the following error when building with gcc-4.4.1:

cc1: warnings being treated as errors
part_efi.c: In function 'test_part_efi':
part_efi.c:265: error: dereferencing pointer 'pgpt_pte' does break strict-aliasing rules
part_efi.c:257: note: initialized from here

This was caused by 9444380 "disk: part_efi: fix **pgpt_pte == NULL, hangs
on Tegra3" using the wrong type for a variable, and casting it.

Signed-off-by: Stephen Warren <swarren@nvidia.com>
Change-Id: Iac2ef212414be5dc9787680241d3ae15ba271d6f
Reviewed-on: http://git-master/r/109005
Reviewed-by: Automatic_Commit_Validation_User
Reviewed-by: Tom Warren <twarren@nvidia.com>
GVS: Gerrit_Virtual_Submit
Reviewed-by: Allen Martin <amartin@nvidia.com>
Tested-by: Arun G <arg@nvidia.com>